-- | This module provides functions to compose functions generated from
--   @'Signal'@s and @'SignalGen'@s.
module WhatIsThisGame.Utils.Compose where

--------------------
-- Global Imports --
import Prelude hiding ((.))
import Control.Wire

----------
-- Code --

-- | Composing functions generated by a @'Wire'@.
(!.) :: Monad m => Wire s e m a (c -> d) -> Wire s e m a (b -> c) -> Wire s e m a (b -> d)
(!.) w1 w2 = (.) <$> w1 <*> w2
